version: "3.9"

services:
  playwright:
    build:
      context: .
    environment:
      - GREP_TEST=${GREP_TEST}
      - PLAYWRIGHT_URL=${PLAYWRIGHT_URL}
    volumes:
      - ./test-results:/app/test-results
