# .github/workflows/ui-tests.yml
name: "Amazon playwright UI Tests"

on: push
env:
  TEST_NAME1: "see the main page"
  TEST_NAME2: "see the reqular main page"
  AMAZON_URL: "https://www.amazon.de/"
  PLAYWRIGHT_URL: ${{ secrets.PLAYWRIGHT_URL }}

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test -g "$TEST_NAME1"

      - name: Upload Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-result artifacts
          path: test-results
  reqular-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test -g "$TEST_NAME2"

      - name: Upload Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-result artifacts
          path: test-results
