# .github/workflows/ui-tests.yml
name: "Amazon playwright UI Tests"

on: push
env:
  TEST_NAME1: "see the main page"
  TEST_NAME2: "see the reqular main page"
  AMAZON_URL: "https://www.amazon.de/"
  PLAYWRIGHT_URL: ${{ secrets.PLAYWRIGHT_URL }}

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - name: Install Dependencies
        run: |
          if [ "${{ steps.cache-npm.outputs.cache-hit }}" != "true" ]; then
           npm ci
          else
           echo "Dependencies are cached. Skipping npm install."
          fi

  run-eslint:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Restore Node Modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
      - name: Run ESLint
        run: npm run lint

  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run tests
        run: GREP_TEST="see the main page" docker compose up --exit-code-from playwright

  reqular-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run tests
        env:
          GREP_TEST: "see the reqular main page"
        run: docker compose up --exit-code-from playwright
