# .github/workflows/ui-tests.yml
name: "Amazon playwright UI Tests"

on: push
env:
  TEST_NAME1: "see the main page"
  TEST_NAME2: "see the reqular main page"
  AMAZON_URL: "https://www.amazon.de/"
  PLAYWRIGHT_URL: ${{ secrets.PLAYWRIGHT_URL }}

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Upload Artifacts for Testing
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules

  run-eslint:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Download Test Artifacts
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: node_modules
      - name: LS
        run: ls node_modules/.bin
      - name: Run ESLint
        run: npm run lint

  smoke-test:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Download Test Artifacts
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: node_modules
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test -g "$TEST_NAME1"

      - name: Upload Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-result smoke artifacts
          path: test-results
  reqular-test:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Download Test Artifacts
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: node_modules
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test -g "$TEST_NAME2"

      - name: Upload Artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-result reqular artifacts
          path: test-results
