# .github/workflows/ui-tests.yml
name: "Amazon playwright UI Tests"

on: push
env:
  TEST_NAME1: "see the main page"
  TEST_NAME2: "see the reqular main page"

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test -g "$TEST_NAME1"
  reqular-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test -g "$TEST_NAME2"
